### ISSUE TITLE
Fetch Anime/Manga List

### ISSUE THREAD

**Issue by irfan-dahir** [irfan-dahir/jikan#18]
Via URL: https://myanimelist.net/malappinfo.php?u=Nekomata1037&status=all&type=anime/manga

Parse XML into JSON and respond.

```php
$jikan->list($username, $type);
```

```
GET https://jikan.me/list/username/anime
GET https://jikan.me/list/username/manga
```

**Comment by ThePromidius** [comment]
is this working?

**Comment by irfan-dahir** [comment]
@ThePromidius Sorry, this feature was discontinued back in August 2017.
It was basically a JSON wrapper of this URL `https://myanimelist.net/malappinfo.php?u=Nekomata1037&status=all&type=anime`

where `u` is the username, `status` is the progress on the item (plan to watch, on hold, watching, etc) and `type` is as you know it. More on the usage [here](https://stackoverflow.com/a/30725062)

This returns in XML, you can easily XML -> JSON.

**Comment by ThePromidius** [comment]
Well I found a way to do it with this:
https://kuristina.herokuapp.com/anime/ThePromidius.json

**Comment by irfan-dahir** [comment]
@ThePromidius Great!
