### ISSUE TITLE
Score Synopsis and Status are not being parsed for Manga

### ISSUE THREAD

**Issue by BlackSynder** [irfan-dahir/jikan#32]
Anime has everything fine, but manga seems to be missing these three specifically.

**Comment by irfan-dahir** [comment]
@BlackSynder Added! 

Major changes have been pushed to Jikan. 
Have a read here: https://myanimelist.net/forum/?topicid=1616529&show=0#msg51137277

**Comment by BlackSynder** [comment]
Thanks! Great work!

**Comment by irfan-dahir** [comment]
Thanks, It should be fixed now. 

If you find any other issues, do let me know! :)

**Comment by BlackSynder** [comment]
will do!
