### ISSUE TITLE
Return non-200 status code when Anime not found

### ISSUE THREAD

**Issue by zunjae** [irfan-dahir/jikan#41]
Example link: https://jikan.me/api/anime/16067232

Returning a non-200 status code allows me to deliver feedback to the user that makes more sense. Right now I need to look in the message to figure out what is wrong.

I completely understand why it returns 200... but I'd rather prefer the status in the HTTP Status code.

**Comment by irfan-dahir** [comment]
You're right. Will be added in the next update.

**Comment by irfan-dahir** [comment]
Added! Let me know if there's anything else.
