### ISSUE TITLE
[User List] Support updating a list

### ISSUE THREAD

**Issue by BlackSynder** [irfan-dahir/jikan#42]
Adding an anime/manga to a list

**Comment by irfan-dahir** [comment]
Why not use the official API for that? If integrated into Jikan, it'll behave like a wrapper.

**Comment by irfan-dahir** [comment]
It seems they've announced it themselves here: https://myanimelist.net/forum/?topicid=1632480

**Comment by BlackSynder** [comment]
Ah I see. Thanks.
